### ISSUE TITLE
Doesn't work with angular 8 unless you declare d3 as a const

### ISSUE THREAD

**Issue by MarvinvR** [bumbeishvili/d3-organization-chart#13]
Hi, on the very first line you declare d3 but with angular 8 it will only work if you declare it as a const.

**Comment by bumbeishvili** [comment]
Hello, I haven't integrated it with angular yet, so I haven't really thought about that

I suggest just including  `TreeChart` class into the app,  from 
https://github.com/bumbeishvili/d3-organization-chart/blob/master/index.js

and using it same way as you would use normal class in angular app.

You also will need d3 to be accessible

`import * as d3 from 'd3'`

This is the code which you will need to add at the top of the file

**Comment by MarvinvR** [comment]
Yea I thought so, but everything else seems to work ok (so far), so you really just have to change it to a contsant. :)

**Comment by bumbeishvili** [comment]
I am not sure how will it work in vue demo or  (or react) and also in other places, where that code is currently integrated, so I'll wait for a more appropriate time to make that change

**Comment by bumbeishvili** [comment]
Just a note - I created vue, react and angular integration demos, so I will be closing this issue

https://github.com/bumbeishvili/d3-organization-chart/blob/master/README.md#integrations
