### ISSUE TITLE
Change the starting position

### ISSUE THREAD

**Issue by caginbektas** [bumbeishvili/d3-organization-chart#15]
Hello David,

Could you please help me to find the starting position? (Since I am trying to use it horizontal, I need to start from middle left, instead of middle top)

**Comment by bumbeishvili** [comment]
Here - https://github.com/bumbeishvili/d3-organization-chart/blob/master/index.js#L107

```javascript
  // Rescale container element accordingly
  attrs.centerG.attr('transform', ` translate(${calc.centerX}, ${calc.nodeMaxHeight / 2}) scale(${attrs.initialZoom})`)
```

**Comment by caginbektas** [comment]
` // Add one more container g element, for better positioning controls
        attrs.centerG = chart.patternify({
            tag: 'g',
            selector: 'center-group'
        })
            .attr('transform', `translate(${calc.centerX},${calc.nodeMaxHeight / 2}) scale(${attrs.initialZoom})`);`

actually it was worked with that line. It looks all okay now :)

**Comment by bumbeishvili** [comment]
@caginbektas What do you mean? Did you make changes in that line?  That's what I was referring

**Comment by caginbektas** [comment]
Hi,
You were referring the line number 107 but it did not work with that line, I tried the line number 227 then it worked.

**Comment by bumbeishvili** [comment]
Right,I missed that line

**Comment by caginbektas** [comment]
Thank you so much for help, appreciated
