### ISSUE TITLE
Zoom level limitation

### ISSUE THREAD

**Issue by caginbektas** [bumbeishvili/d3-organization-chart#16]
Hi David,

Is there any way to set minimum and/or maximum zoom level?

**Comment by bumbeishvili** [comment]
Not explicitly

but here is relevant pieces of code

1. https://stackoverflow.com/a/51459099/5369006
2. https://github.com/bumbeishvili/d3-organization-chart/blob/master/index.js#L167

**Comment by caginbektas** [comment]
Thank you so much, i solved in this way,

`        behaviors.zoom = d3.zoom().scaleExtent([0.5, 10]).on("zoom", zoomed)
`
instead of 

`        behaviors.zoom = d3.zoom().on("zoom", zoomed)
`
