### ISSUE TITLE
Conditionally adding div elements

### ISSUE THREAD

**Issue by learn-d3** [bumbeishvili/d3-organization-chart#19]
Using your reference:
https://observablehq.com/@bumbeishvili/d3-v5-organization-chart 
 
I'm trying to add conditionally progress bar, but to no avail.
You hints would help a lot:

Partial snippet in my angular component:
```
d3.hierarchy(dataSource)
.descendants()
 .map(d => {
  .............

template:
'<div *ngIf="${isApplicable}">
        <ngb-progressbar type="${progressColor}" [value]="80" height="9px">
                                80%
</ngb-progressbar>
</div>'
```
.................
}

**Comment by bumbeishvili** [comment]
As I see, you are trying to use angular component within d3 area, which is not possible, you have to use raw HTML
