### ISSUE TITLE
Possible to have two nodes at the same time?

### ISSUE THREAD

**Issue by jerrychong25** [bumbeishvili/d3-organization-chart#24]
Hi all,

I am wondering if d3-organization-chart support two nodes like following screenshot:

<img width="489" alt="Screenshot 2020-08-03 at 10 17 40 AM" src="https://user-images.githubusercontent.com/15714095/89139856-a5086400-d572-11ea-880e-9252946cb522.png">

Just like a family tree with combination of husband + wife.

If yes, how could I can configure this?

Thanks.

**Comment by bumbeishvili** [comment]
Hello, no it does not support that

I have no idea how you can reconfigure 

If I were you I would start from this [Stackoverflow example](https://stackoverflow.com/questions/31245751/how-do-you-create-a-family-tree-in-d3-js)

**Comment by jerrychong25** [comment]
@bumbeishvili Thanks for the clarification.

In the end, I used **dTree** to achieve my requirement.

**Comment by bumbeishvili** [comment]
Thank you for the info, good to know

**Comment by prasannapattam** [comment]
I also have similar requirement. I am working on a family tree where I need to show both husband & wife with children.
What I have done is treated Husband & Wife as one node and used nodeContent to show them as two nodes. Also some tweaking on the links between the nodes.

![Family Tree](https://github.com/bumbeishvili/org-chart/assets/4832935/3109fb0b-19bb-4e33-a12b-1699159aa02b)

Thanks for the highly customizable org-chart.

**Comment by jerrychong25** [comment]
> I also have similar requirement. I am working on a family tree where I need to show both husband & wife with children. What I have done is treated Husband & Wife as one node and used nodeContent to show them as two nodes. Also some tweaking on the links between the nodes.
> 
> ![Family Tree](https://user-images.githubusercontent.com/4832935/242960806-3109fb0b-19bb-4e33-a12b-1699159aa02b.png)
> 
> Thanks for the highly customizable org-chart.

@prasannapattam 

Nice one!

Mind to share sample code for this?

**Comment by prasannapattam** [comment]
Here is the Vue code (work in progress and not the best code).

```javascript
<template>
  <div class="chart-container" style="width: 100%; min-height: inherit"></div>
</template>
<style lang="sass">
.person-member
  display: flex
  flex-wrap: wrap
  height: 40px
  align-items: center
  justify-content: center
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.24)

.male-member
  background: radial-gradient(circle, #B0E0E6 0%, #00CED1 100%)
.female-member
  background: radial-gradient(circle, #FFB6C1 0%, #FF69B4 100%)
div.line
  margin-top: 13px
  width: 5px
  hr
    border-style: solid
    border-width: 5px 0 0

.person-icon
  padding-top: 3px
  width:40px
  height:30px

.person-name
  text-align: left
  justify-content: center

.selected-person
  border: 4px solid #152785
</style>

<script setup lang="ts">
import * as d3 from 'd3';
import { OrgChart } from '../services/d3-org-chart';
import { onMounted } from 'vue';
import { FamilyModel } from '../models/family-model';
import { PersonModel } from 'src/models/person-model';
import maleIcon from 'src/assets/images/male.svg';
import femaleIcon from 'src/assets/images/female.svg';

// class variables
let chart: OrgChart;
let treeData: FamilyModel[];

onMounted(() => {
  treeData = getTreeData(); // get the family data
  renderChart(treeData);
});

function renderChart(data: FamilyModel[]) {
  // variables used in tree
  const nodeWidth = 150;
  const nodeWidthSpouse = 320;
  const gapWidth = nodeWidthSpouse - nodeWidth * 2;
  const linkShift = Math.round((nodeWidth + gapWidth) / 2);
  const nodeHeight = 40; 
  const nodeHeightSpouse = 40;

  chart = new OrgChart()
    .container('.chart-container')
    .data(data)
    .onNodeClick((nodeId: string) => nodeClicked(nodeId))
    .rootMargin(100)
    .nodeWidth((d) =>
      d.data.spouseId !== undefined ? nodeWidthSpouse : nodeWidth
    )
    .nodeHeight((d) =>
      d.data.spouseId !== undefined ? nodeHeightSpouse : nodeHeight
    )
    .childrenMargin((d) => 75)
    .siblingsMargin((d) => 30)
    // .compactMarginBetween((d) => 175)
    // .compactMarginPair((d) => 80)
    .linkUpdate(function (d, i, arr) {
      // drawing the connecting line
      d3.select(this)
        .attr('stroke', (d) => 'lightgray')
        .attr('stroke-width', (d) => 2);
      //.attr('stroke-dasharray', '4,4');
    })
    .nodeContent(function (d, i, arr, state) {
      const personData: FamilyModel = <FamilyModel>d.data;

      let nodeHtml = '<div class="row">';
      if (personData.gender === 'F') {
        nodeHtml += getPersonNodeContent(personData, 'spouse');
        nodeHtml += getPersonNodeContent(personData, 'child');
      } else {
        nodeHtml += getPersonNodeContent(personData, 'child');
        nodeHtml += getPersonNodeContent(personData, 'spouse');
      }
      nodeHtml += '</div>';

      return nodeHtml;
    })
    .compact(false);

  // changing the links for persons who has spouse
  chart.layoutBindings().top.linkX = (d) => {
    if (d.data.spouseId === undefined) {
      return d.x;
    } else if (d.data.gender === 'M') {
      return d.x - linkShift;
    } else {
      return d.x + linkShift;
    }
  };

  chart.render().fit();
}

function getPersonNodeContent(personData: FamilyModel, personType: string) {
  const person: PersonModel = <PersonModel>{};

  if (personType === 'spouse') {
    person.id = personData.spouseId;
    person.name = personData.spouseName;
    person.gender = personData.spouseGender;
  } else {
    person.id = personData.id;
    person.name = personData.name;
    person.gender = personData.gender;
  }

  if (person.id === undefined) {
    return '';
  } else {
    let personCssClass, personIcon;
    if (person.gender === 'M') {
      personCssClass = 'male-member';
      personIcon = maleIcon;
    } else {
      personCssClass = 'female-member';
      personIcon = femaleIcon;
    }
    let nodeContent = '';
    if (personData.spouseId !== undefined && person.gender === 'F') {
      nodeContent += '<div class="line"><hr/></div>';
    }
    nodeContent += `
        <div class="col ${personCssClass} person-member person-${person.id} ${
            <div class="col-grow">
            <img src="${personIcon}" class="person-icon" />
          </div>
          <div class="col person-name">${person.name}</div>
        </div>`;
    return nodeContent;
  }
}

function nodeClicked(personId: string) {
  chart.setCentered(personId);
  // for each of the childrent set expanded
  treeData.forEach((d) => {
    if (d.parentId === personId) {
      chart.setExpanded(d.id);
    }
  });

  chart.render().fit();
}

function getTreeData() {
  const treeData: FamilyModel[] = [
    {
      id: 'L1',
      name: 'Grand Father Kumar',
      gender: 'M',
      parentId: '',
      spouseId: 'L1S',
      spouseName: 'Grand Mother Kumar',
      spouseGender: 'F',
    },
    {
      id: 'L1C1',
      name: 'Son 1 Kumar',
      gender: 'M',
      parentId: 'L1',
      spouseId: 'L1C1S',
      spouseName: 'Daughter in law',
      spouseGender: 'F',
    },
    {
      id: 'L1C2',
      name: 'Daughter Devi',
      gender: 'F',
      parentId: 'L1',
      spouseId: 'L1C2S',
      spouseName: 'Son in law',
      spouseGender: 'M',
    },
    {
      id: 'L1C3',
      name: 'Son 2 Kumar',
      gender: 'M',
      parentId: 'L1',
      spouseId: 'L1C3S',
      spouseName: 'Daughter in law',
      spouseGender: 'F',
    },
    { id: 'L1C1C1', name: 'Grand Daughter 1', gender: 'F', parentId: 'L1C1' },
    { id: 'L1C1C2', name: 'Grand Son 1', gender: 'M', parentId: 'L1C1' },
    { id: 'L1C2C1', name: 'Grand Daughter 2', gender: 'F', parentId: 'L1C2' },
    { id: 'L1C2C2', name: 'Grand Daughter 3', gender: 'F', parentId: 'L1C2' },
    { id: 'L1C3C1', name: 'Grand Son 2', gender: 'M', parentId: 'L1C3' },
    { id: 'L1C3C2', name: 'Grand Son 3', gender: 'M', parentId: 'L1C3' },
  ];

  return treeData;
}
</script>

**Comment by jerrychong25** [comment]
> Here is the Vue code (work in progress and not the best code).
> 
> ```js
> <template>
>   <div class="chart-container" style="width: 100%; min-height: inherit"></div>
> </template>
> <style lang="sass">
> .person-member
>   display: flex
>   flex-wrap: wrap
>   height: 40px
>   align-items: center
>   justify-content: center
>   box-shadow: 0 2px 4px rgba(0, 0, 0, 0.24)
> 
> .male-member
>   background: radial-gradient(circle, #B0E0E6 0%, #00CED1 100%)
> .female-member
>   background: radial-gradient(circle, #FFB6C1 0%, #FF69B4 100%)
> div.line
>   margin-top: 13px
>   width: 5px
>   hr
>     border-style: solid
>     border-width: 5px 0 0
> 
> .person-icon
>   padding-top: 3px
>   width:40px
>   height:30px
> 
> .person-name
>   text-align: left
>   justify-content: center
> 
> .selected-person
>   border: 4px solid #152785
> </style>
> 
> <script setup lang="ts">
> import * as d3 from 'd3';
> import { OrgChart } from '../services/d3-org-chart';
> import { onMounted } from 'vue';
> import { FamilyModel } from '../models/family-model';
> import { PersonModel } from 'src/models/person-model';
> import maleIcon from 'src/assets/images/male.svg';
> import femaleIcon from 'src/assets/images/female.svg';
> 
> // class variables
> let chart: OrgChart;
> let treeData: FamilyModel[];
> 
> onMounted(() => {
>   treeData = getTreeData(); // get the family data
>   renderChart(treeData);
> });
> 
> function renderChart(data: FamilyModel[]) {
>   // variables used in tree
>   const nodeWidth = 150;
>   const nodeWidthSpouse = 320;
>   const gapWidth = nodeWidthSpouse - nodeWidth * 2;
>   const linkShift = Math.round((nodeWidth + gapWidth) / 2);
>   const nodeHeight = 40; 
>   const nodeHeightSpouse = 40;
> 
>   chart = new OrgChart()
>     .container('.chart-container')
>     .data(data)
>     .onNodeClick((nodeId: string) => nodeClicked(nodeId))
>     .rootMargin(100)
>     .nodeWidth((d) =>
>       d.data.spouseId !== undefined ? nodeWidthSpouse : nodeWidth
>     )
>     .nodeHeight((d) =>
>       d.data.spouseId !== undefined ? nodeHeightSpouse : nodeHeight
>     )
>     .childrenMargin((d) => 75)
>     .siblingsMargin((d) => 30)
>     // .compactMarginBetween((d) => 175)
>     // .compactMarginPair((d) => 80)
>     .linkUpdate(function (d, i, arr) {
>       // drawing the connecting line
>       d3.select(this)
>         .attr('stroke', (d) => 'lightgray')
>         .attr('stroke-width', (d) => 2);
>       //.attr('stroke-dasharray', '4,4');
>     })
>     .nodeContent(function (d, i, arr, state) {
>       const personData: FamilyModel = <FamilyModel>d.data;
> 
>       let nodeHtml = '<div class="row">';
>       if (personData.gender === 'F') {
>         nodeHtml += getPersonNodeContent(personData, 'spouse');
>         nodeHtml += getPersonNodeContent(personData, 'child');
>       } else {
>         nodeHtml += getPersonNodeContent(personData, 'child');
>         nodeHtml += getPersonNodeContent(personData, 'spouse');
>       }
>       nodeHtml += '</div>';
> 
>       return nodeHtml;
>     })
>     .compact(false);
> 
>   // changing the links for persons who has spouse
>   chart.layoutBindings().top.linkX = (d) => {
>     if (d.data.spouseId === undefined) {
>       return d.x;
>     } else if (d.data.gender === 'M') {
>       return d.x - linkShift;
>     } else {
>       return d.x + linkShift;
>     }
>   };
> 
>   chart.render().fit();
> }
> 
> function getPersonNodeContent(personData: FamilyModel, personType: string) {
>   const person: PersonModel = <PersonModel>{};
> 
>   if (personType === 'spouse') {
>     person.id = personData.spouseId;
>     person.name = personData.spouseName;
>     person.gender = personData.spouseGender;
>   } else {
>     person.id = personData.id;
>     person.name = personData.name;
>     person.gender = personData.gender;
>   }
> 
>   if (person.id === undefined) {
>     return '';
>   } else {
>     let personCssClass, personIcon;
>     if (person.gender === 'M') {
>       personCssClass = 'male-member';
>       personIcon = maleIcon;
>     } else {
>       personCssClass = 'female-member';
>       personIcon = femaleIcon;
>     }
>     let nodeContent = '';
>     if (personData.spouseId !== undefined && person.gender === 'F') {
>       nodeContent += '<div class="line"><hr/></div>';
>     }
>     nodeContent += `
>         <div class="col ${personCssClass} person-member person-${person.id}"  onclick="window.selectedPersonId = '${person.id}';">
>             <div class="col-grow">
>             <img src="${personIcon}" class="person-icon" />
>           </div>
>           <div class="col person-name">${person.name}</div>
>         </div>`;
>     return nodeContent;
>   }
> }
> 
> function nodeClicked(personId: string) {
>   chart.setCentered(personId);
>   // for each of the childrent set expanded
>   treeData.forEach((d) => {
>     if (d.parentId === personId) {
>       chart.setExpanded(d.id);
>     }
>   });
> 
>   chart.render().fit();
> }
> 
> function getTreeData() {
>   const treeData: FamilyModel[] = [
>     {
>       id: 'L1',
>       name: 'Grand Father Kumar',
>       gender: 'M',
>       parentId: '',
>       spouseId: 'L1S',
>       spouseName: 'Grand Mother Kumar',
>       spouseGender: 'F',
>     },
>     {
>       id: 'L1C1',
>       name: 'Son 1 Kumar',
>       gender: 'M',
>       parentId: 'L1',
>       spouseId: 'L1C1S',
>       spouseName: 'Daughter in law',
>       spouseGender: 'F',
>     },
>     {
>       id: 'L1C2',
>       name: 'Daughter Devi',
>       gender: 'F',
>       parentId: 'L1',
>       spouseId: 'L1C2S',
>       spouseName: 'Son in law',
>       spouseGender: 'M',
>     },
>     {
>       id: 'L1C3',
>       name: 'Son 2 Kumar',
>       gender: 'M',
>       parentId: 'L1',
>       spouseId: 'L1C3S',
>       spouseName: 'Daughter in law',
>       spouseGender: 'F',
>     },
>     { id: 'L1C1C1', name: 'Grand Daughter 1', gender: 'F', parentId: 'L1C1' },
>     { id: 'L1C1C2', name: 'Grand Son 1', gender: 'M', parentId: 'L1C1' },
>     { id: 'L1C2C1', name: 'Grand Daughter 2', gender: 'F', parentId: 'L1C2' },
>     { id: 'L1C2C2', name: 'Grand Daughter 3', gender: 'F', parentId: 'L1C2' },
>     { id: 'L1C3C1', name: 'Grand Son 2', gender: 'M', parentId: 'L1C3' },
>     { id: 'L1C3C2', name: 'Grand Son 3', gender: 'M', parentId: 'L1C3' },
>   ];
> 
>   return treeData;
> }
> </script>
> ```
> 
> Here is the corresponding output: ![image](https://user-images.githubusercontent.com/4832935/243114970-62425d4d-09d8-4a6d-8c4d-b7ba222105db.png)

Thanks you very much @prasannapattam !

**Comment by AnkushSarkar10** [comment]
> Here is the Vue code (work in progress and not the best code).
> 
> ```js
> <template>
>   <div class="chart-container" style="width: 100%; min-height: inherit"></div>
> </template>
> <style lang="sass">
> .person-member
>   display: flex
>   flex-wrap: wrap
>   height: 40px
>   align-items: center
>   justify-content: center
>   box-shadow: 0 2px 4px rgba(0, 0, 0, 0.24)
> 
> .male-member
>   background: radial-gradient(circle, #B0E0E6 0%, #00CED1 100%)
> .female-member
>   background: radial-gradient(circle, #FFB6C1 0%, #FF69B4 100%)
> div.line
>   margin-top: 13px
>   width: 5px
>   hr
>     border-style: solid
>     border-width: 5px 0 0
> 
> .person-icon
>   padding-top: 3px
>   width:40px
>   height:30px
> 
> .person-name
>   text-align: left
>   justify-content: center
> 
> .selected-person
>   border: 4px solid #152785
> </style>
> 
> <script setup lang="ts">
> import * as d3 from 'd3';
> import { OrgChart } from '../services/d3-org-chart';
> import { onMounted } from 'vue';
> import { FamilyModel } from '../models/family-model';
> import { PersonModel } from 'src/models/person-model';
> import maleIcon from 'src/assets/images/male.svg';
> import femaleIcon from 'src/assets/images/female.svg';
> 
> // class variables
> let chart: OrgChart;
> let treeData: FamilyModel[];
> 
> onMounted(() => {
>   treeData = getTreeData(); // get the family data
>   renderChart(treeData);
> });
> 
> function renderChart(data: FamilyModel[]) {
>   // variables used in tree
>   const nodeWidth = 150;
>   const nodeWidthSpouse = 320;
>   const gapWidth = nodeWidthSpouse - nodeWidth * 2;
>   const linkShift = Math.round((nodeWidth + gapWidth) / 2);
>   const nodeHeight = 40; 
>   const nodeHeightSpouse = 40;
> 
>   chart = new OrgChart()
>     .container('.chart-container')
>     .data(data)
>     .onNodeClick((nodeId: string) => nodeClicked(nodeId))
>     .rootMargin(100)
>     .nodeWidth((d) =>
>       d.data.spouseId !== undefined ? nodeWidthSpouse : nodeWidth
>     )
>     .nodeHeight((d) =>
>       d.data.spouseId !== undefined ? nodeHeightSpouse : nodeHeight
>     )
>     .childrenMargin((d) => 75)
>     .siblingsMargin((d) => 30)
>     // .compactMarginBetween((d) => 175)
>     // .compactMarginPair((d) => 80)
>     .linkUpdate(function (d, i, arr) {
>       // drawing the connecting line
>       d3.select(this)
>         .attr('stroke', (d) => 'lightgray')
>         .attr('stroke-width', (d) => 2);
>       //.attr('stroke-dasharray', '4,4');
>     })
>     .nodeContent(function (d, i, arr, state) {
>       const personData: FamilyModel = <FamilyModel>d.data;
> 
>       let nodeHtml = '<div class="row">';
>       if (personData.gender === 'F') {
>         nodeHtml += getPersonNodeContent(personData, 'spouse');
>         nodeHtml += getPersonNodeContent(personData, 'child');
>       } else {
>         nodeHtml += getPersonNodeContent(personData, 'child');
>         nodeHtml += getPersonNodeContent(personData, 'spouse');
>       }
>       nodeHtml += '</div>';
> 
>       return nodeHtml;
>     })
>     .compact(false);
> 
>   // changing the links for persons who has spouse
>   chart.layoutBindings().top.linkX = (d) => {
>     if (d.data.spouseId === undefined) {
>       return d.x;
>     } else if (d.data.gender === 'M') {
>       return d.x - linkShift;
>     } else {
>       return d.x + linkShift;
>     }
>   };
> 
>   chart.render().fit();
> }
> 
> function getPersonNodeContent(personData: FamilyModel, personType: string) {
>   const person: PersonModel = <PersonModel>{};
> 
>   if (personType === 'spouse') {
>     person.id = personData.spouseId;
>     person.name = personData.spouseName;
>     person.gender = personData.spouseGender;
>   } else {
>     person.id = personData.id;
>     person.name = personData.name;
>     person.gender = personData.gender;
>   }
> 
>   if (person.id === undefined) {
>     return '';
>   } else {
>     let personCssClass, personIcon;
>     if (person.gender === 'M') {
>       personCssClass = 'male-member';
>       personIcon = maleIcon;
>     } else {
>       personCssClass = 'female-member';
>       personIcon = femaleIcon;
>     }
>     let nodeContent = '';
>     if (personData.spouseId !== undefined && person.gender === 'F') {
>       nodeContent += '<div class="line"><hr/></div>';
>     }
>     nodeContent += `
>         <div class="col ${personCssClass} person-member person-${person.id}"  onclick="window.selectedPersonId = '${person.id}';">
>             <div class="col-grow">
>             <img src="${personIcon}" class="person-icon" />
>           </div>
>           <div class="col person-name">${person.name}</div>
>         </div>`;
>     return nodeContent;
>   }
> }
> 
> function nodeClicked(personId: string) {
>   chart.setCentered(personId);
>   // for each of the childrent set expanded
>   treeData.forEach((d) => {
>     if (d.parentId === personId) {
>       chart.setExpanded(d.id);
>     }
>   });
> 
>   chart.render().fit();
> }
> 
> function getTreeData() {
>   const treeData: FamilyModel[] = [
>     {
>       id: 'L1',
>       name: 'Grand Father Kumar',
>       gender: 'M',
>       parentId: '',
>       spouseId: 'L1S',
>       spouseName: 'Grand Mother Kumar',
>       spouseGender: 'F',
>     },
>     {
>       id: 'L1C1',
>       name: 'Son 1 Kumar',
>       gender: 'M',
>       parentId: 'L1',
>       spouseId: 'L1C1S',
>       spouseName: 'Daughter in law',
>       spouseGender: 'F',
>     },
>     {
>       id: 'L1C2',
>       name: 'Daughter Devi',
>       gender: 'F',
>       parentId: 'L1',
>       spouseId: 'L1C2S',
>       spouseName: 'Son in law',
>       spouseGender: 'M',
>     },
>     {
>       id: 'L1C3',
>       name: 'Son 2 Kumar',
>       gender: 'M',
>       parentId: 'L1',
>       spouseId: 'L1C3S',
>       spouseName: 'Daughter in law',
>       spouseGender: 'F',
>     },
>     { id: 'L1C1C1', name: 'Grand Daughter 1', gender: 'F', parentId: 'L1C1' },
>     { id: 'L1C1C2', name: 'Grand Son 1', gender: 'M', parentId: 'L1C1' },
>     { id: 'L1C2C1', name: 'Grand Daughter 2', gender: 'F', parentId: 'L1C2' },
>     { id: 'L1C2C2', name: 'Grand Daughter 3', gender: 'F', parentId: 'L1C2' },
>     { id: 'L1C3C1', name: 'Grand Son 2', gender: 'M', parentId: 'L1C3' },
>     { id: 'L1C3C2', name: 'Grand Son 3', gender: 'M', parentId: 'L1C3' },
>   ];
> 
>   return treeData;
> }
> </script>
> ```
> 
> Here is the corresponding output: ![image](https://user-images.githubusercontent.com/4832935/243114970-62425d4d-09d8-4a6d-8c4d-b7ba222105db.png)

I LOVE YOU MAN

**Comment by prasannapattam** [comment]
I also implemented multiple spouses. You can check the code at my GitHub project.

https://github.com/prasannapattam/Vamsam/blob/main/Vamsam.UI/src/components/TreeComponent.vue


![Screenshot 2023-07-18 215430](https://github.com/bumbeishvili/org-chart/assets/4832935/697a0489-9f9f-4ef9-8f5c-d3855300acb2)

**Comment by prasannapattam** [comment]
> In your implementation, can both parents have their own parents? (both husband and wife have their own parent)

This is not my requirement as of now. Buy will be in future.

As this was built using D3 Tree, there has to be one root node always. If I have to implement, I will keep a dummy root node and build the two tree structures (Husband and Wife trees). When drawing the tree, I will hide the dummy root node.

**Comment by mohcinsarrar** [comment]
Hi all,
i want using org-chart to create my family tree tools, i have used the implementation of @prasannapattam to show husband and wife in the same level and their children in next level, now i have a family tree where a husband has tow wifes with each wife he has children, i want the code from this link https://github.com/prasannapattam/Vamsam/blob/main/Vamsam.UI/src/components/TreeComponent.vue but the link is introuvable, please if anyones has the code from the link 
Best Regards

**Comment by jerrychong25** [comment]
> Hi all, i want using org-chart to create my family tree tools, i have used the implementation of @prasannapattam to show husband and wife in the same level and their children in next level, now i have a family tree where a husband has tow wifes with each wife he has children, i want the code from this link https://github.com/prasannapattam/Vamsam/blob/main/Vamsam.UI/src/components/TreeComponent.vue but the link is introuvable, please if anyones has the code from the link Best Regards

@prasannapattam Could assist on this? Thanks.

**Comment by prasannapattam** [comment]
I copied the TreeComponent.vue to a gist file. If you have any questions on this, please post here.
https://gist.github.com/prasannapattam/f2ac32972c8df4ffafc0bd255492b479

**Comment by jerrychong25** [comment]
> I copied the TreeComponent.vue to a gist file. If you have any questions on this, please post here. https://gist.github.com/prasannapattam/f2ac32972c8df4ffafc0bd255492b479

Thanks @prasannapattam !

**Comment by mohcinsarrar** [comment]
thanks @prasannapattam
