### ISSUE TITLE
Unable to zoom or translate when using in angular project

### ISSUE THREAD

**Issue by sai-github** [bumbeishvili/d3-organization-chart#25]
I followed the steps as per your sample angular stackblitz example. I get the following error

```
core.js:4197 ERROR TypeError: Cannot read property 'transform' of undefined
    at TreeChart.zoomed (d3-org-chart.js:1185)
    at SVGSVGElement.<anonymous> (d3-org-chart.js:167)
    at Dispatch.call (dispatch.js:57)
    at Gesture.emit (zoom.js:219)
    at Gesture.zoom (zoom.js:207)
    at SVGSVGElement.wheeled (zoom.js:262)
    at SVGSVGElement.<anonymous> (on.js:3)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:27424)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
```

I am using this particular version
```
Angular CLI: 10.0.7
Node: 10.22.0
OS: win32 x64

Angular: 10.0.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.7
@angular-devkit/build-angular     0.1000.7
@angular-devkit/build-optimizer   0.1000.7
@angular-devkit/build-webpack     0.1000.7
@angular-devkit/core              10.0.7
@angular-devkit/schematics        10.0.7
@angular/cli                      10.0.7
@ngtools/webpack                  10.0.7
@schematics/angular               10.0.7
@schematics/update                0.1000.7
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
```

I tried to import `index.js` into my project and I still face the same error. Is there any quick workaround to fix the issue?

**Comment by sai-github** [comment]
As a work around I tried to download downlaod `d3.v5.min.js` and `index.js` from your jsfiddle example and used it in my project. I get the below error, I see this in angular stackblitz example as well.

```
core.js:4197 ERROR TypeError: Cannot read property 'length' of null
    at Object.T [as max] (d3.v5.min.js:2)
    at Chart.render (index.js:138)
    at D3SampleChartComponent.updateChart (d3-sample-chart.component.ts:52)
    at D3SampleChartComponent.ngAfterViewInit (d3-sample-chart.component.ts:33)
    at callHook (core.js:3038)
    at callHooks (core.js:3008)
    at executeInitAndCheckHooks (core.js:2960)
    at refreshView (core.js:7242)
    at refreshComponent (core.js:8325)
    at refreshChildComponents (core.js:6964)
```

**Comment by bumbeishvili** [comment]
Ok, Investigating now

**Comment by bumbeishvili** [comment]
Ok, found an issue.

It was trying to initialize the org chart without passing data first.

Here is updated example - https://stackblitz.com/edit/d3-org-chart-angular-integration

I made changes in `d3-org-chart.compontent .ts`

Please use same d3 version as in stackblitz example

**Comment by sai-github** [comment]
I don't see the issue in your stackblitz example but when I download the example and try to build it on local I get error with (same thing happened yesterday when trying to build)

```
node_modules/@angular/forms/forms.d.ts(4352,9): error TS1086: An accessor cannot be declared in an ambient context.

i ｢wdm｣: Failed to compile.
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
```

**Comment by bumbeishvili** [comment]
@sai-github quick googling shows that,   that looks like angular versions mismatch. 

https://stackoverflow.com/questions/60131331/error-ts1086-an-accessor-cannot-be-declared-in-an-ambient-context-in-angular-9

**Comment by sai-github** [comment]
Yes, I tried changing angular-devkit but no luck. I am surprised on why it is working in stackblitz but but fails on my local?

**Comment by bumbeishvili** [comment]
Probably because @angular/cli,  @angular/core

I will download it once I find a time and will test it if it works locally, will post results here

**Comment by aizaiz** [comment]
@bumbeishvili the fix to this problem is to change dependency 
**From**
```
"dependencies": {
    "d3": "*"
  }
```

**To**
```
"dependencies": {
    "d3": "5.16.0"
  }
```

d3 has released v6 and if you put "d3": "*" in package.json it'll try to use v6 which is not compatible with d3-org-chart@1.0.13

**Comment by bumbeishvili** [comment]
@aizaiz I am not sure if whether that's connected to the problem or not. In the [stackblitz example](https://stackblitz.com/edit/d3-org-chart-angular-integration?file=package.json), the d3 version is already pinned to `5.15.1` version.

Just for the note: v2 version of this tree  will be based on v6 - https://github.com/bumbeishvili/d3-organization-chart/issues/14

**Comment by aizaiz** [comment]
@bumbeishvili tried to reinstall the package on stackblitz example, it'll produce the error

**Comment by bumbeishvili** [comment]
Ah, I thought you were referring to Stackblitz examples only. Thanks for the PR, I will merge it tomorrow and will update the npm version as well

**Comment by aizaiz** [comment]
Nice!, will be waiting

**Comment by bumbeishvili** [comment]
Merged and updated [npm version](https://www.npmjs.com/package/d3-org-chart)
