### ISSUE TITLE
Images required? 

### ISSUE THREAD

**Issue by emmanuelrflores** [bumbeishvili/d3-organization-chart#26]
For my use, we don't need the images. If I take out the `nodeImage` from the example you have, I get a 'cannot read property 'url' of undefined' at the "add images to pattern" part of the code where it tries to look for an image. Is there something that needs to be done to ignore the image?

The code below is from Chrome dev tools.
```
// Add images to patterns
        const patternImages = patterns.patternify({
            tag: 'image',
            selector: 'pattern-image',
            data: d => [d]
        })
            .attr('x', 0)
            .attr('y', 0)
            .attr('height', ({
                imageWidth
            }) => imageWidth)
            .attr('width', ({
                imageHeight
            }) => imageHeight)
            .attr('xlink:href', ({
                data
            }) => data.nodeImage.url) <------ HERE
            .attr('viewbox', ({
                imageWidth,
                imageHeight
            }) => `0 0 ${imageWidth * 2} ${imageHeight}`)
            .attr('preserveAspectRatio', 'xMidYMin slice')
```

**Comment by emmanuelrflores** [comment]
Actually, I'm seeing in the [latest version](https://github.com/bumbeishvili/d3-organization-chart/blob/master/index.js#L529) there's a check if ` data.nodeImage` exists, but in the version I've pulled from npm it has the above.

**Comment by emmanuelrflores** [comment]
Awesome! I'll close this out once it's done. Thank you for the quick reply!

**Comment by bumbeishvili** [comment]
Published

https://unpkg.com/d3-org-chart@1.0.13/index.js
