### ISSUE TITLE
Is there a way to get native html event when user click a node?

### ISSUE THREAD

**Issue by aizaiz** [bumbeishvili/d3-organization-chart#29]
@bumbeishvili  Is there a way to get native html event when a user click a node?

**Comment by bumbeishvili** [comment]
Yes, there is a global `d3.event` object available that time

Note - it will be removed when I convert this graph to d3.v6, instead the user will receive it as a first argument, in node Click Hander function

**Comment by aizaiz** [comment]
@bumbeishvili Thanks. 
Can't wait for the upgrade to d3.v6 released
