### ISSUE TITLE
(Question) What is the best way to catch error of "no root id", "multiple root id", or "parent node is not found"?

### ISSUE THREAD

**Issue by aizaiz** [bumbeishvili/d3-organization-chart#31]
### Question?
I know there are several conditions where org-chart will trigger an error:
1. when there are no root id
2. when there are more than one root id
3. when parent node has child node as parent id (a.k.a cycle)
4. etc

I could use ```try catch``` when rendering the org-chart, but is there a better way to catch errors above?

**Comment by bumbeishvili** [comment]
I am not sure, I guess you have to clean & validate data before that happens

**Comment by aizaiz** [comment]
@bumbeishvili is ```d3.stratify()``` has catch error method?

**Comment by bumbeishvili** [comment]
I don't think so, I am not sure though

**Comment by aizaiz** [comment]
Okay noted. Thanks 👍
