### ISSUE TITLE
nodeIcon is not used / ignored

### ISSUE THREAD

**Issue by sidyes** [bumbeishvili/d3-organization-chart#36]
I saw that the usage of the provided `nodeIcon` is ignored (cf. `node-icon-image` in your code).
Why is it like that? I would love to use a custom icon for collapsing nodes.

**Comment by bumbeishvili** [comment]
@sidyes nodeIcon was used for different functionality (to display icons inside nodes), theoretically, you can use node icons already inside nodes, it's just you won't be able to attach  expand&collapse actions to them.

This is the relevant code piece which is responsible for expand & collapse note icon settings, for now, it's just `+`, `-` symbols.
https://github.com/bumbeishvili/d3-organization-chart/blob/master/index.js#L893

I am thinking about changing this functionality in v2  version

**Comment by sidyes** [comment]
Ah good to know. Is it somehow possible to inject an Angular component as a template?
I need to implement some additional functionality within a node.

**Comment by bumbeishvili** [comment]
>  Is it somehow possible to inject an Angular component as a template

No, it's not possible

> I need to implement some additional functionality within a node.

I think in that case you will need to make changes to the chart itself

Please follow how `onNodeClick` action is implemented, it may help you
https://github.com/bumbeishvili/d3-organization-chart/blob/master/index.js#L25

**Comment by sidyes** [comment]
Thanks for your help, I solved it by adding a `document event listener` that listens to clicks on certain elements within a node.

**Comment by bumbeishvili** [comment]
Great to hear, I was not sure that would work and I did not suggest it
