### ISSUE TITLE
Data of size 1 is not supported

### ISSUE THREAD

**Issue by sidyes** [bumbeishvili/d3-organization-chart#41]
**Describe the bug**
Data of size 1 is not supported and leads to error `TypeError: Cannot read property 'forEach' of undefined` happening here:
```
// Collapse all children at first
attrs.root.children.forEach(d => this.collapse(d));

// Then expand some nodes, which have `expanded` property set
 attrs.root.children.forEach(d => this.expandSomeNodes(d));
```

**To Reproduce**
1. Provide data in correct format of size 1
2. Set data and call render like `this.chart.data(data).render()`
3. See error in console an no org chart drawn

**Expected behavior**
Org chart should show the root element

Could you please fix this?

**Comment by bumbeishvili** [comment]
Interesting use case

Yes I will fix it, but not sure when

**Comment by sidyes** [comment]
I fixed this issue with this simple [PR](https://github.com/bumbeishvili/d3-organization-chart/pull/43).

Could you make a small patch for that?

**Comment by bumbeishvili** [comment]
Looks good, merging...

**Comment by sidyes** [comment]
Could you publish a patch `1.1.2` for [that](https://www.npmjs.com/package/d3-org-chart)?

**Comment by bumbeishvili** [comment]
Pushed
