### ISSUE TITLE
Horizontal layout?

### ISSUE THREAD

**Issue by davidlinc1** [bumbeishvili/d3-organization-chart#42]
**Is your feature request related to a problem? Please describe.**
Not a problem, but just a preference - in my project I'd like to display the chart elements expanding out horizontally to the right, rather than top-down. Example:

![image](https://user-images.githubusercontent.com/14900082/100703313-1eb13280-3358-11eb-91ab-aedcad78ff1c.png)

**Describe the solution you'd like**
Ideally this would be a parameter that could be passed as a part of the exposed variables, but I also think it might be possible just to modify the JS file to change the way that the elements are laid out. 

I was intrigued by the way the nodes were positioned, as well as how the paths were generated in diagonal(), but I haven't quite played around enough to be able to alter this logic to do what I want - to orientate descendants horizontally towards the right, rather than spreading out top-to-bottom.

![Code_OvO3fa3rdU](https://user-images.githubusercontent.com/14900082/100702996-8915a300-3357-11eb-8591-8524e24af11b.png)

**Describe alternatives you've considered**
I tried my hand at modifying the JS file and looked around for an option or configuration I might have missed, but I came up empty - maybe @bumbeishvili has thoughts on how to make it work this way? If not, no worries, thanks anyway for this fantastic project.

**Comment by davidlinc1** [comment]
Wow, and of course minutes later I find your successor project that already supports this!

https://observablehq.com/d/e106c59dbd9f6151

Great work!

**Comment by bumbeishvili** [comment]
@davidlinc1 please note, the new one uses the latest d3.v6 and the earlier one used d3.v5

Just copy-paste would not work, since d3 changed event parameters, meaning zooming & panning and node click handling won't work as expected.

So you:
* Either will need to to change the current version
* Or upgrade your d3 version

**Comment by davidlinc1** [comment]
Yup sorry forgot to mention I did upgrade d3 to v6. For my workflow it was as simple as `yarn remove d3` (since I installed with `yarn add d3@5.16.0` initially when I was using the code from this repo), then just another `yarn add d3` to grab the latest! 

When I found this project I was like 😩👌💞

**Comment by bumbeishvili** [comment]
In the new, dev version (development branch, uses d3 v7),4 layout types are implemented which can be changed at runtime

Layout can be set using

```javascript
chart.layout('left')
chart.layout('top')
chart.layout('right')
chart.layout('bottom')
```

https://github.com/bumbeishvili/d3-organization-chart/blob/b64f9ef60f9eeff48969df2ecead9a5504c501f3/src/d3-org-chart.js#L64


https://user-images.githubusercontent.com/6873202/126049326-a4b49ae4-f5ca-4a28-9710-92675c78ace1.mp4
