### ISSUE TITLE
Error missing: node

### ISSUE THREAD

**Issue by ebitsdev** [bumbeishvili/d3-organization-chart#49]
Hello,

I have forked the repository and trying to make it work with my data. I have not been successful in generating a chart using the data I have, which mirrors the one in the source repository.

What I am missing or doing wrong? I am using the email addresses of the managers as the parentNodeId.
I am using d3-org-chart version 1.1.13 of the script along with d3.v5.16

Thank you for your reply.

---
```Error
missing: manager22@company.com
▼ 2 stack frames were expanded.
stratify
https://91hlv.csb.app/node_modules/d3-hierarchy/src/stratify.js:34:29
TreeChart.render
https://91hlv.csb.app/node_modules/d3-org-chart/index.js:179:13
▲ 2 stack frames were expanded.
eval
/index.js:19:5
  16 |     .svgHeight(window.innerWidth)
  17 |     .initialZoom(0.6)
  18 |     .onNodeClick((d) => console.log(d + " node clicked"))
> 19 |     .render();
     |     ^
  20 | });
  21 | 
```
Data: https://gist.githubusercontent.com/ebitsdev/df73973abe2992885bd643ff952dedb9/raw/e93bc8556b300a005b3de8e6b2b7bffc88a40ed0/org_chart_data.json.
Project:  https://codesandbox.io/s/broken-framework-91hlv?file=/index.js

**Comment by bumbeishvili** [comment]
@ebitsdev it looks like, your nodeId and parentNodeId aren't matching each other. Therefore d3 can't build a hierarchy from it

<img width="398" alt="Screenshot 2021-03-09 at 23 18 38" src="https://user-images.githubusercontent.com/6873202/110525275-d4490a00-812d-11eb-9e3a-c81556a0d7ad.png">

**Comment by ebitsdev** [comment]
I just tried to use the email as the nodeId and parentNodeId, but when I do I get the error message: multiple roots.
How and where would you fix the problem?

**Comment by ebitsdev** [comment]
Thanks for your help, I finally solved the issue. There two parentNodeId that were null. After fixing that the duplicate parentNodeId the chart shows up now.
