### ISSUE TITLE
Increase space between two levels

### ISSUE THREAD

**Issue by rajat-sf** [bumbeishvili/d3-organization-chart#51]
hi,

How can we increase vertical space between two levels 

PFA for better illustration.
https://user-images.githubusercontent.com/77266357/115686655-0c6f7980-a377-11eb-8c3b-d39d06e59bd6.png

Thanks

**Comment by bumbeishvili** [comment]
This is the relevant line I believe

https://github.com/bumbeishvili/d3-organization-chart/blob/master/index.js#L148

**Comment by rajat-sf** [comment]
Thanks @bumbeishvili
