### ISSUE TITLE
Disable zooming and drag

### ISSUE THREAD

**Issue by pulkit-b** [bumbeishvili/d3-organization-chart#52]
How can I disable the zoom and drag.

**Comment by bumbeishvili** [comment]
This is a relevant code piece

https://github.com/bumbeishvili/d3-organization-chart/blob/master/index.js#L219

**Comment by pulkit-b** [comment]
I'm using the npm package and not in the mood to keep this code in my local codebase

**Comment by bumbeishvili** [comment]
Another way (theoretical) is just to use css and disable pointer events to the generated svg completelly .

 Not sure if it will work but it's worth for a try

**Comment by bumbeishvili** [comment]
Closing and will reopen if the above solution prove worthless
