### ISSUE TITLE
Update the chart

### ISSUE THREAD

**Issue by caginbektas** [bumbeishvili/d3-organization-chart#8]
Hi David,

I've tried to call the update() method with a new set of json source. 

> VM2961:1 Uncaught ReferenceError: update is not defined
> at <anonymous>:1:1

is it possible to re-draw the graph with new data?

**Comment by bumbeishvili** [comment]
@caginbektas  if you want data update, you should pass new data and invoke `render` method

```javascript
chartReference
.data(newData)
.render()
```

**Comment by caginbektas** [comment]
thank you! :)
