### ISSUE TITLE
Question best practice

### ISSUE THREAD

**Issue by AndorLundgren** [bumbeishvili/d3-organization-chart#9]
Hi,

I will most probably use your code dt-organization-chart, nice coding.
I am new to github interactions and have a question.

I have made so far only smaller changes and was planning tackle custom name for direct and total subordinates. Nothing fancy but I also may need to change the position somehow.

I found out by browsing forks that it has already been done:
https://github.com/rhodief/d3-organization-chart

So what is the best practice?
Should I ask you for the feature and then ask him to insert it into your code or should i ask him if i could copy it to my fork?

Best regards

Andor

**Comment by bumbeishvili** [comment]
Hi Andor, I think best thing would be to fork code and fit it to your needs

As for descendants (subordinates), I think currently it's not very flexible and I plan to change implementation logic in the future

Already created #10 issue

**Comment by AndorLundgren** [comment]
OK, I will for and wait. Thank you for the fast answer!

**Comment by bumbeishvili** [comment]
@AndorLundgren I dont know when I will find time to work on this

**Comment by bumbeishvili** [comment]
In the new version (v2), you will be able to specify node content HTML string. 

Data will have special attributes attached

`_directSubordinates`
`_totalSubordinates`
`_highlighted`
`_highlightedUpToTheParent`

Those properties you can use when building single node content  (useful for conditional styling or for content itself)

Apart from that, you will have access to d3 wrapped node, which means:
* You will be able to directly access parent `node.parent`
* You will be able to directly access children `node.children`
* You will be able to invoke `node.descendants()` function to get all descendants for the node
*  You will be able to invoke `node.ancestors()` function to get all descendants for node

<img width="597" alt="Screenshot 2021-07-18 at 00 43 06" src="https://user-images.githubusercontent.com/6873202/126048931-aba74a39-b4c0-4919-b176-72b3465955e5.png">
